db:
   image: "mongo:3.0.3"
sql:
  image: "mysql:5.7.9"
  environment:
    - "MYSQL_USER=ensibs"
    - "MYSQL_PASSWORD=Ensibs56"
    - "MYSQL_ROOT_PASSWORD=Ensibs56"
    - "MYSQL_DATABASE=test"
  ports:
    - "3306:3306"
init:
  build: initialization
  links:
    - "sql:mysql"  
  ports:
    - "5000:5000"
refpersons:
  build: referentiel-personnes
  links:
     - "sql:mysql"
  ports:
    - "88:5000"
app:
  build: webapp
  links:
    - "db:mongo"
    - "refpersons:personnes"
  ports:
    - "8080:8080"
