sql:
  image: "mysql:5.7.9"
  environment:
    - "MYSQL_USER=ensibs"
    - "MYSQL_PASSWORD=Ensibs56"
    - "MYSQL_ROOT_PASSWORD=Ensibs56"
    - "MYSQL_DATABASE=test"
  ports:
    - "3306:3306"
init:
  build: initialization
  links:
    - "sql:mysql"  
  ports:
    - "5000:5000"
refpersons:
  build: persons-repository
  links:
    - "sql:mysql"
  ports:
    - "88:5000"
app:
  build: webapp
  links:
    - "refpersons:persons-directory"
  ports:
    - "8080:8080"
